### ISSUE TITLE
Add user account so that API is not publicly accessible?

### ISSUE THREAD

**Issue by stefandesu** [Erikvl87/docker-languagetool#29]
Hi,

is it somehow possible to create a user account so that only I can access the API? I was looking at [the possible config options](https://github.com/languagetool-org/languagetool/blob/120699fd7166c9712893bd8704b4d612570c28d7/languagetool-server/src/main/java/org/languagetool/server/Server.java#L123-L160). The only thing that sounds like it might work is set `maxTextLength` to 0 and set a `secretTokenKey`, but I can't find out how to generate that key and how I would configure my clients.

Any ideas? Thanks a lot!

**Comment by Erikvl87** [comment]
Hi @stefandesu, unfortunately, I need to redirect you to [the main LanguageTool repository](https://github.com/languagetool-org/languagetool/issues), since this repo is only dockerizing that application. I have no knowledge on these configuration options.

From my perspective, the only advice I could give you is to use the Docker [Publish or expose port](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) configuration to only listen to incoming requests from, for example, an NGINX host which you configure with your authentication requirements.
