### ISSUE TITLE
Reduce Amount of Suggestions 

### ISSUE THREAD

**Issue by HighKo** [Erikvl87/docker-languagetool#32]
On languagetool.org a maximum of 5 suggestions is returned via the api, but we sometimes get 80 or more from this container and our frontend is unable decide which ones are the best. Is there a way to limit the amount on server side? 

With langtool_maxSpellingSuggestions no suggestions are returned at all when the limit is breached.

Thank you for your time.

**Comment by Erikvl87** [comment]
Hi @HighKo, unfortunately, I need to redirect you to [the main LanguageTool repository](https://github.com/languagetool-org/languagetool/issues), since this repo is only dockerizing that application.

Maybe this has to do with some custom configuration at the public LanguageTool API (e.g. because of the presence of n-gram config, enabled/disabled rules or categories).
