### ISSUE TITLE
Question: How to set the loglevel?

### ISSUE THREAD

**Issue by thomas-mc-work** [Erikvl87/docker-languagetool#82]
Hello,

currently the log level is set to `INFO`. How can I set it to another level?

Thanks!

**Comment by Erikvl87** [comment]
Hi @thomas-mc-work, hopefully you'll be able to set the log level after I tested and merged https://github.com/Erikvl87/docker-languagetool/pull/76.

**Comment by Erikvl87** [comment]
Hello @thomas-mc-work, the [6.4 tag has been released](https://hub.docker.com/r/erikvl87/languagetool/tags), which enables you to overwrite the logback.xml configuration file to adjust the log level. Please take a look at the [README.md](https://github.com/Erikvl87/docker-languagetool?tab=readme-ov-file#overwrite-logging-configuration) file for instructions. 

Could you let me know if this works for you?

**Comment by thomas-mc-work** [comment]
That was working perfectly! Thank you very much :kissing_heart: 

Two suggestions:

- I've set it to `WARNING` which I think might be the best default value
- I've mounted it with the `:ro` flag as it's never written to

**Comment by Erikvl87** [comment]
Hi @thomas-mc-work, I am glad to hear that this is working for you. I'll consider updating the instructions with the `:ro` flag.

I have contemplated setting the default to `WARNING` too, but I decided against it because it would require overwriting LanguageTool's default configuration with a "custom" default specifically for this Dockerized version. If LanguageTool updates their defaults in the future, those changes would not be reflected automatically in this Dockerized version. Moreover, I believe that LanguageTool should establish any sensible default settings themselves.
